<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="tower_with_segments" params="parent *origin">
    <xacro:property name="segment_radius" value="0.225"/>
    <xacro:property name="tower_height" value="0.5775"/>
    <xacro:property name="tower_shift" value="0.1915"/>
    <link name="tower_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://robotino_description/meshes/modules/tower_with_segments.dae" scale="0.01 0.01 0.01"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 ${tower_height/2 + tower_shift}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${tower_height}" radius="${segment_radius}"/>
        </geometry>
      </collision>
    </link>

    <joint name="tower_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="tower_link"/>
      <xacro:insert_block name="origin"/>
    </joint>
  </xacro:macro>
</robot>