<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="omniwheel" params="name angle parent">
    <xacro:property name="wheel_radius" value="0.0625"/>
    <xacro:property name="wheel_thickness" value="0.062"/>
    <xacro:property name="wheel_mass" value="0.485"/>
    <xacro:property name="wheel_distance" value="0.1811"/>
    <link name="${name}_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="file://$(find robotino_description)/meshes/robotino3/omniwheel_rotacaster_r3_1258_85.dae" scale="0.01 0.01 0.01"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${radians(90)} 0 0"/>
        <geometry>
          <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${wheel_mass}"/>
        <inertia ixx="${wheel_mass*(3*wheel_radius**2 + wheel_thickness**2)/12}" ixy="0.0" ixz="0.0"
                iyy="${(wheel_mass * wheel_radius**2)/2}" iyz="0.0"
                izz="${wheel_mass*(3*wheel_radius**2 + wheel_thickness**2)/12}"/>
      </inertial>
    </link>

    <joint name="${name}_joint" type="continuous">
      <parent link="${parent}"/>
      <child link="${name}_link"/>
      <origin xyz="${wheel_distance * cos(angle)} ${wheel_distance * sin(angle)} ${wheel_radius}" rpy="0 0 ${angle + radians(90)}"/>
      <axis xyz="0 1 0" rpy="0 0 0"/>	
    </joint>
  </xacro:macro>
</robot>